
****************Train start!*****************
Traceback (most recent call last):
  File "main.py", line 191, in <module>
    result, best_model_state, optimizer_st = train(data_loader, args)
  File "/opt/ml/code/trainer.py", line 250, in train
    criterion = create_criterion(args.criterion)
  File "/opt/ml/code/loss.py", line 115, in create_criterion
    raise RuntimeError('Unknown loss (%s)' % criterion_name)
RuntimeError: Unknown loss (LabelSmoothingLoss)